# Facebook Pytorch 1.0 教程

## 1. What is PyTorch?
**PyTorch的组成部分：**
1. automatic differentiation engine
2. Ndarray library with GPU support
3. Distributed training
4. Production-ready C++ runtime
5. gradient based optimization package
6. Utilities(data loading,etc.)

# 2. ndarray library
Pytorch被称为神经网络的numpy，为什么呢？因为`np.ndarry` <-> `torch.Tensor`中的操作非常相似，加上GPU，所以运算非常快，下面我们比较一下：

* 首先是numpy 代码：

In [2]:
import numpy as np


N,D_in,H,D_out = 54,1000,100,10

# 创建随机输入和输出
x = np.random.randn(N , D_in)
y = np.random.randn(N , D_out)

# 随机初始化权值
w1 = np.random.randn(D_in,H)
w2 = np.random.randn(H, D_out)

learning_rate = 1e-6

for t in range(500):
    # forward 前向过程
    h = x.dot(w1)
    h_relu = np.maximum(h,0)
    y_pred = h_relu.dot(w2)
    
    # 计算loss
    loss = np.square(y_pred - y).sum()
    print(t,"turn: ", loss)
    
    # backprop 后向过程
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)
    
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2
    

0 turn:  25902431.879741177
1 turn:  19667915.881960966
2 turn:  15703056.330939017
3 turn:  12327716.761904921
4 turn:  9261643.786908623
5 turn:  6650974.979294437
6 turn:  4634447.263955887
7 turn:  3192417.3091512616
8 turn:  2215607.1908576544
9 turn:  1570944.481600485
10 turn:  1145688.8724153633
11 turn:  862917.4575967597
12 turn:  669830.348605209
13 turn:  533807.5029864854
14 turn:  434891.61297826376
15 turn:  360650.2440819749
16 turn:  303279.8470286433
17 turn:  257781.675638947
18 turn:  220997.61671311493
19 turn:  190788.10689599218
20 turn:  165636.85301751236
21 turn:  144447.24898729956
22 turn:  126464.36986866029
23 turn:  111101.4644300804
24 turn:  97903.51607467321
25 turn:  86501.50336650021
26 turn:  76614.88797254513
27 turn:  68004.53541816722
28 turn:  60481.781052643564
29 turn:  53888.58197762249
30 turn:  48100.6526167174
31 turn:  43004.21008457731
32 turn:  38502.26470520457
33 turn:  34520.42071436035
34 turn:  30992.228937691594
35 turn:  27861.52

646.9065655999876
78 turn:  597.2102554244776
79 turn:  551.4949372286114
80 turn:  509.43816786447627
81 turn:  470.72208427066596
82 turn:  435.08496201494575
83 turn:  402.26805141435295
84 turn:  372.0138251592045
85 turn:  344.124383895698
86 turn:  318.41523612349715
87 turn:  294.71431845797423
88 turn:  272.8390813070329
89 turn:  252.65103823189216
90 turn:  234.01506179948947
91 turn:  216.8087551164233
92 turn:  200.9244261267948
93 turn:  186.25221741727066
94 turn:  172.68760621635136
95 turn:  160.15031280140974
96 turn:  148.56054005894765
97 turn:  137.8372175992073
98 turn:  127.91991325859985
99 turn:  118.75138800348756
100 turn:  110.26487474124909
101 turn:  102.41039768764666
102 turn:  95.1333265255108
103 turn:  88.39346526737651


104 turn:  82.15044613473059
105 turn:  76.36425084544203
106 turn:  70.99933464423403
107 turn:  66.02571442281021
108 turn:  61.414244476108024
109 turn:  57.13907851868351
110 turn:  53.171494445953726
111

 turn:  49.488627371120366
112 turn:  46.069920157606646
113 turn:  42.89515486747504
114 turn:  39.94756853571388
115 turn:  37.20978180900774
116 turn:  34.66745046500081
117 turn:  32.30360732980086
118 turn:  30.107300971386387
119 turn:  28.065622663412583
120 turn:  26.167292335773162
121 turn:  24.402515659890298
122 turn:  22.762056006581915
123 turn:  21.23401209293017
124 turn:  19.812268254217525


125 turn:  18.48901937523243
126 turn:  17.257567573709732
127 turn:  16.11117562819771
128 turn:  15.043502591390881
129 turn:  14.04868752991913
130 turn:  13.12194477495441
131 turn:  12.258587995268186
132 turn:  11.453983009205043
133 turn:  10.70432784966357
134 turn:  10.005809973393832
135 turn:  9.353662130801748
136 turn:  8.745497939650331
137 turn:  8.178370554828074
138 turn:  7.649167636163728
139 turn:  7.155592945780702
140 turn:  6.694686495495442
141 turn:  6.2644647309643915
142 turn:  5.862864648807858
143 turn:  5.4878020372902085
144 turn:  5.137555907235001
145 turn:  4.810568565660715
146 turn:  4.505044509274221
147 turn:  4.219514133614725
148 turn:  3.9525850952351815
149 turn:  3.703065383916044
150 turn:  3.4699032882551144
151 turn:  3.2518666689491784
152 turn:  3.0479213403836214
153 turn:  2.8571417611194967
154 turn:  2.678658947873913
155 turn:  2.511679391008706
156 turn:  2.35553283532696
157 turn:  2.2094521153289444
158 turn:  2.0725620396257836
1

 turn:  0.03613783222419072
226 turn:  0.034106639194329956
227 turn:  0.03219130338800727
228 turn:  0.03038517778430556
229 turn:  0.028681588807520943
230 turn:  0.027074947610945345
231 turn:  0.025561666174693944
232 turn:  0.024132491931736076
233 turn:  0.02278405652966845
234 turn:  0.021511990869381888
235 turn:  0.020312006192290937
236 turn:  0.01918024365458272
237 turn:  0.018112754958608757
238 turn:  0.017104968884360652
239 turn:  0.01615375179708508
240 turn:  0.01525632833756257
241 turn:  0.014409156008280471
242 turn:  0.013609815964507128
243 turn:  0.012855567552176672
244 turn:  0.0121437109394431
245 turn:  0.011471336100578575
246 turn:  0.010836611541906033
247 turn:  0.010237433991086873
248 turn:  0.009672211056378603
249 turn:  0.00913836268610371
250 turn:  0.008634246914576304
251 turn:  0.0081581151190163
252 turn:  0.007708590885434447
253 turn:  0.00728405749317642
254 turn:  0.006883270375649825
255 turn:  0.006504794654337492
256 turn:  0.00614725296

334 turn:  8.061175915059923e-05
335 turn:  7.630478851167481e-05
336 turn:  7.222998583053305e-05
337 turn:  6.837333738253106e-05
338 turn:  6.472206563795398e-05
339 turn:  6.126706406838408e-05
340 turn:  5.799840992027617e-05
341 turn:  5.490385132341202e-05
342 turn:  5.1974346769910984e-05
343 turn:  4.9203306370805166e-05
344 turn:  4.657871977932011e-05
345 turn:  4.409529028559907e-05
346 turn:  4.1745624660792006e-05
347 turn:  3.952013064859082e-05
348 turn:  3.741356884119265e-05
349 turn:  3.542060156858078e-05
350 turn:  3.3533779546417576e-05
351 turn:  3.174752076868103e-05
352 turn:  3.005717396162182e-05
353 turn:  2.8456440277215083e-05
354 turn:  2.694151207641914e-05
355 turn:  2.5507608710717385e-05
356 turn:  2.4149800209581932e-05
357 turn:  2.2864786125790542e-05
358 turn:  2.1648662869251148e-05
359 turn:  2.0496921600090074e-05
360 turn:  1.940650390396995e-05
361 turn:  1.8374549444551858e-05
362 turn:  1.7397406651527572e-05
363 turn:  1.6472867115506033e-

 turn:  2.4994869660446724e-07
441 turn:  2.367592876629368e-07
442 turn:  2.242656869666005e-07
443 turn:  2.1243093394464778e-07
444 turn:  2.0121997937206645e-07
445 turn:  1.906060338530331e-07
446 turn:  1.8054847961415881e-07
447 turn:  1.7102398491841443e-07
448 turn:  1.620019033962644e-07
449 turn:  1.5345564152705192e-07
450 turn:  1.4536301071424392e-07
451 turn:  1.376945601679692e-07
452 turn:  1.3043210036805967e-07
453 turn:  1.23553469646272e-07
454 turn:  1.1703800258889685e-07
455 turn:  1.1086830792404084e-07
456 turn:  1.0502178576557481e-07
457 turn:  9.948406778537476e-08
458 turn:  9.423862553689013e-08
459 turn:  8.927124623895969e-08
460 turn:  8.456513574634718e-08
461 turn:  8.010638077657792e-08
462 turn:  7.588336534223352e-08
463 turn:  7.188298002446148e-08
464 turn:  6.809505433059679e-08
465 turn:  6.450624766230859e-08
466 turn:  6.110596316920782e-08
467 turn:  5.788514096792775e-08
468 turn:  5.483453412040916e-08
469 turn:  5.194532054647214e-08
470

下面我们来看tensor是怎么解决这个问题的。

In [9]:
# TO-DO
import torch

dtype = torch.FloatTensor

print(dtype)

<class 'torch.FloatTensor'>


可以看到numpy.ndarray和torch.tensor是非常相似的。

* 构造一个 $ 5 \times 3 $ 的0矩阵

In [6]:
from __future__ import print_function
import torch

x = torch.Tensor(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.8946e-42, 0.0000e+00],
        [0.0000e+00, 1.1692e-19, 0.0000e+00]])


* 随机初始化两个矩阵

In [10]:
x = torch.rand(5,3)
print(x)

tensor([[0.3405, 0.6669, 0.4768],
        [0.1587, 0.8933, 0.8746],
        [0.4759, 0.2391, 0.2873],
        [0.7888, 0.8154, 0.0488],
        [0.9692, 0.3559, 0.4046]])


* 获取`size()`

In [12]:
print(x.size())

torch.Size([5, 3])


* 切片操作

In [13]:
print(x[:,1])

tensor([0.6669, 0.8933, 0.2391, 0.8154, 0.3559])


* 构造全0张量并且转换为numpy格式：

In [15]:
a = torch.ones(5)
print(a)
print(type(a))

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


* 加

In [16]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


可以看出，`tensor.numpy()`是一个浅拷贝，换言之，使用这种转换的时候是一个引用.
继续看下面的操作

* 将`numpy.ndarray`转换为`torch.tensor`

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)

np.add(a , 1 ,out = a)

print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


* 最后查看一下如何转化为GPU运行（一般只需要全局设计一下即可）

In [20]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

# 3. automatic differentiation engine

Pytorch 的关键在于自动求导Autograd技术，这个具体的操作请查看evernote笔记