# Mofan Tutorial
***

> Pytorch 可以被称为 神经网络界的 Numpy

## 1. Pytorch 和 Numpy 对比

In [1]:
import torch
import numpy as np

np_data = np.arange(6).reshape(2,3)
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()

print("Numpy = \n", np_data,"\n",
      "Torch = \n", torch_data,"\n",
      "Tensor2Array = \n",tensor2array,"\n")

Numpy = 
 [[0 1 2]
 [3 4 5]] 
 Torch = 
 tensor([[0, 1, 2],
        [3, 4, 5]]) 
 Tensor2Array = 
 [[0 1 2]
 [3 4 5]] 



上面这里展示了如何将numpy和tensor进行查找，下面我们将介绍一些简单的运算符。

In [4]:
# 具体请查询官网
import torch
import numpy as np

data = [[1,2],[3,4]]
tensor = torch.FloatTensor(data)

print(
    "\nnumpy = ", np.matmul(data,data),
    "\ntorch = ", torch.mm(tensor,tensor)
)


numpy =  [[ 7 10]
 [15 22]] 
torch =  tensor([[ 7., 10.],
        [15., 22.]])


注意到numpy的matmul 和 dot 的差异，因此有必要看对比一下

In [6]:
import numpy as np
import torch

data = [[1,2],[3,4]]
tensor = torch.tensor(data)
data = np.array(data)
tensor_dot_answer = torch.tensordot(tensor,tensor)
print(
    "\nnumpy:" , data.dot(data),
    "\ntorch:" , tensor.dot(tensor)
)

RuntimeError: dot: Expected 1-D argument self, but got 2-D