# Mofan Tutorial
***

> Pytorch 可以被称为 神经网络界的 Numpy

In [2]:
import torch
import numpy as np

np_data = np.arange(6).reshape(2,3)
torch_data = torch.from_numpy(np_data)


print("Numpy = \n", np_data,"\n",
      "Torch = \n", torch_data,"\n")

Numpy = 
 [[0 1 2]
 [3 4 5]] 
 Torch = 
 tensor([[0, 1, 2],
        [3, 4, 5]]) 

